/* COMPTON ONE: FIX — language pack: Tagalog (tl) + Simplified Chinese (zh).
   Loads after app.js, before app.ui.js. Three jobs:
   1. Full chrome translations (T.tl / T.zh) layered over English as fallback.
   2. Bundle-boundary patches: the tested engine (window.C1) only knows en/es,
      so receipt + emergency + ICS paths are coerced honestly (the UI says so).
   3. Catalog titles and tile-group labels in tl/zh.
   The engine itself (bundle.js) is never edited. */
(function () {
  var X = window.C1X;
  if (!X) return;
  var C1 = X.C1, T = X.T;

  var TL = {
      eyebrow: 'Pag-navigate sa mga serbisyo ng lungsod · Compton, California',
      h1a: 'Isang problema.',
      h1b: 'Isang malinaw na daan pasulong.',
      lede: 'Ilarawan ang problema sa serbisyo ng lungsod sa sarili mong salita. Tinutulungan ka ng COMPTON ONE: FIX na ihanda ang tamang impormasyon, mahanap ang opisyal na susunod na hakbang, at subaybayan kung ano ang mangyayari.',
      cta: 'Magsimula ng report',
      ctademo: 'Patakbuhin ang demo scenario',
      trust: 'Ginawa para sa malinaw na mga susunod na hakbang. Ang report mo ay mananatili sa ilalim ng kontrol mo.',
      supported: 'Ang mga maaari naming i-route ngayon',
      howlabel: 'Paano ito gumagana',
      privacy: 'Humihingi kami ng tinatayang bloke, hindi ang eksaktong address mo. Walang government ID. Walang pampublikong pangalan ng nagre-report. Maaari mong burahin ang case anumang oras.',
      disclosure: 'Hackathon prototype: inihahanda at sinusubaybayan ng app na ito ang aksyon mo. Hindi ito direktang nagsusumite sa City of Compton.',
      step1: 'Hakbang 1 ng 5 — Sabihin sa amin kung ano ang nangyari',
      step2: 'Hakbang 2 ng 5 — Isang mabilisang tanong',
      step3: 'Hakbang 3 ng 5 — Ang plano mo sa aksyon · isang tawag na lang',
      step4: 'Hakbang 4 ng 5 — Huwag iwala ang sinulid',
      step5: 'Hakbang 5 ng 5 — Ang mga case mo',
      intakeH: 'Hindi mo kailangang malaman kung anong department.',
      what: 'Ano ang nangyari?',
      whatHint: 'Ilarawan ang problema kung paano mo ito ikukuwento sa kapitbahay. Pinakamahusay ang payak na mga salita. (Sa ngayon, pinakamahusay ang pagtugma kapag English o Español ang ginamit.)',
      examples: 'O magsimula sa isang halimbawa:',
      intakePriv: 'Huwag isama ang mga pangalan, plaka ng sasakyan, o akusasyon laban sa isang partikular na tao. Ilarawan kung ano ang nakita mo.',
      analyze: 'Hanapin ang tamang daan',
      back: '← Bumalik',
      printFallback: 'Hinarang ng browser mo ang pag-print. Gamitin ang menu ng browser → Print, o kumuha ng screenshot ng receipt na ito.',
      clarifyH: 'Isang mabilisang tanong',
      yes: 'Oo, tama iyan',
      notsure: 'Hindi, o hindi ako sigurado',
      chooseH: 'Maaaring dalawang magkaibang serbisyo ito',
      chooseHint: 'Wala kaming sapat na katiyakan para pumili para sa iyo. Piliin ang tumutugma sa nakita mo.',
      unsupH: 'Hindi namin maitugma ito',
      unsupBody: '{n} na serbisyo ng lungsod ang nire-route ng COMPTON ONE: FIX, pero hindi kami huhula ng department para sa iyo, dahil sayang ang oras mo kapag mali ang hula. Subukan ang ibang salita, piliin ang pinakamalapit na serbisyo sa ibaba, o tawagan ang main line ng City of Compton sa (310) 605-5500.',
      saved: 'Susunod: subaybayan ang case na ito',
      print: 'I-print o i-save ang PDF',
      edit: 'Baguhin ang sagot ko',
      tlH: 'Timeline ng case',
      confLabel: 'Confirmation number na natanggap mo',
      confHint: 'Ilagay kung ano ang ibinigay sa iyo ng lungsod: service request number, reference code, o ang petsa at pangalan ng taong nakausap mo.',
      confWhere: 'Saan nanggagaling ang numerong ito? Ibinibigay ito ng lungsod kapag tumawag ka o nagsumite — itanong: "Maaari ba akong humingi ng service request number para sa report na ito?" Isulat dito kung ano man ang ibigay nila, para may lakas ang follow-up mo.',
      saveConf: 'I-save ang confirmation',
      resolve: 'Markahan bilang nalutas',
      del: 'Burahin ang case na ito',
      simNote: 'Simulated sa prototype na ito: ang mga SMS reminder at anumang acknowledgment mula sa lungsod. Ang lahat ng iba pa sa pahinang ito ay totoong gawi.',
      toDash: 'Pumunta sa mga case ko →',
      dashH: 'Ang mga case mo',
      demoData: 'Demo data. Ipinapakita ng mga case na ito ang outcome loop at hindi ito mga totoong record ng lungsod.',
      yourCases: 'Aktibo at kamakailan',
      newReport: 'Magsimula ng panibagong report',
      footer: 'Ang COMPTON ONE: FIX ay isang independiyenteng prototype. Hindi ito pinapatakbo ng City of Compton at hindi nito isinusumite ang mga report para sa iyo.',
      owner: 'Sino ang humahawak nito',
      evidence: 'Ihanda ang mga detalyeng ito',
      prohibited: 'Huwag isama',
      action: 'Gawin ang opisyal na susunod na hakbang',
      script: 'Ang sasabihin',
      save: 'I-save ang matatanggap mo',
      follow: 'Mag-follow up',
      sources: 'Saan ito nagmula',
      yousaid: 'Ang sinabi mo sa amin',
      conf: 'Katiyakan ng pagtugma',
      notsub: 'Hindi nagsusumite sa lungsod para sa iyo ang prototype na ito.',
      verified: 'Opisyal na beripikado',
      needsconf: 'Kailangan ng kumpirmasyon',
      mCase: 'KASO',
      mStatus: 'KATAYUAN',
      useWhen: 'Gamitin kapag',
      reaches: 'Aabot sa',
      noSla: 'Hindi pa naglalabas ang lungsod ng oras ng pagtugon para sa serbisyong ito, kaya ito ay paalala para sa iyo — hindi pangako mula sa lungsod.',
      stopFirst: 'Huminto at tumawag muna sa 9-1-1 kung makakita ka ng alinman sa mga ito:',
      empty: 'Pakilarawan muna kung ano ang nangyari.',
      reopen: 'Buksan muli ang case na ito',
      evDone: 'Nakuhang ebidensya',
      keepH: 'Panatilihin ang case na ito sa phone na ito?',
      keepBody: 'Sa ngayon, mawawala ang case na ito kapag isinara mo ang pahina. Maaari naming i-save ito sa device na ito para makabalik ka rito. Ang nai-save: ang tinype mo, ang natugmang serbisyo, ang confirmation number mo, at ang follow-up date mo. Walang ipinapadala kahit saan at walang tumutukoy sa iyo. Maaari mong burahin lahat sa isang pindutan.',
      keepYes: 'I-save sa device na ito',
      keepNo: 'Hindi, pansamantala lang',
      keepOn: 'Naka-save lang sa device na ito',
      keepOff: 'Hindi naka-save — magtatapos ang case na ito kapag isinara mo ang pahina',
      keepFail: 'Hindi pinayagan ng device na ito ang pag-save. Gumagana pa rin ang case, pero hindi ito mananatili kapag isinara ang pahina.',
      erase: 'Burahin lahat ng naka-save',
      erased: 'Nabura na ang lahat ng naka-save sa device na ito.',
      savedCases: 'Naka-save sa device na ito',
      noSaved: 'Wala pang naka-save sa device na ito.',
      openCase: 'Buksan',
      cal: 'I-download ang calendar file (.ics)',
      gcal: 'Idagdag sa Google Calendar',
      calDone: '✓ Na-download ang reminder. Buksan ang file para idagdag ang follow-up sa calendar mo — o gamitin ang Google Calendar button para sa one-tap na pagdagdag.',
      gcalDone: '✓ Binubuksan ang Google Calendar — suriin ang event at pindutin ang Save.',
      msgH: 'Message studio',
      msgHint: 'Handang ipadalang mga salita para sa lungsod. Sagutan ang anumang nasa [mga bracket], tapos i-copy at i-paste ito sa form ng lungsod, sa email, o sa mga notes mo.',
      msgReport: 'Unang report',
      msgFollow: 'Follow-up',
      msgEscalate: 'Eskalasyon',
      msgCopy: 'Kopyahin ang mensahe',
      msgCopied: '✓ Nakopya — i-paste ito sa form ng lungsod, sa email, o sa mga notes mo.',
      nextH: 'Ano ang susunod na mangyayari',
      nextS1: 'Tipunin ang mga detalye sa itaas at i-check ang mga ito habang nagpapatuloy ka.',
      nextS2: 'Gawin ang opisyal na hakbang — tumawag o buksan ang form. Ang script at mensahe sa ibaba ang sasabihin mo.',
      nextS3: 'Humingi ng service request o confirmation number, tapos magpatuloy sa pagsubaybay.',
      nextS4: 'Bumalik sa follow-up date at itala kung ano ang nangyari.',
      evReady: 'Handa na ang lahat ng detalye. Maaari ka nang makipag-ugnayan sa lungsod.',
      evReadyBtn: 'Pumunta sa opisyal na hakbang ↓',
      evDoneBtn: 'Nakipag-ugnayan na ako sa lungsod — i-save ang confirmation ko →',
      afterContactText: 'Nakipag-ugnayan ka na ba sa lungsod? I-save ang confirmation number na ibinigay nila para may lakas ang follow-up mo.',
      afterContactBtn: 'I-save ang confirmation ko →',
      privLabel: 'Ang naitala ng app na ito tungkol sa iyo',
      privNote: 'Bawat event na nagawa ng session na ito ay nakalista sa ibaba, nang buo. Walang paglalarawang tinype mo, walang address, at walang confirmation number ang makapapasok sa log na ito — ang analytics layer ay tumatanggap lang ng maikling nakapirming token, at tinatanggihan ang lahat ng iba pa. Walang ipinapadala kahit saan; nananatili ito sa device mo.',
      evLabel: 'Event log ng session',
      evNone: 'Wala pang naitatalang event.',
      stepNames: 'Ilarawan|Tugma|Aksyon|Subaybay|Nalutas',
      how1t: 'Ilarawan',
      how1d: 'Sabihin kung ano ang nangyari sa sarili mong salita. Hindi kailangan ng mga pangalan ng department.',
      how2t: 'Tugma',
      how2d: 'Itinutugma namin ito sa isa sa {n} na beripikadong serbisyo ng lungsod at ipinapakita namin sa iyo ang pinagmulan nito.',
      how3t: 'Aksyon',
      how3d: 'Makakakuha ka ng listahan ng ebidensya, ang opisyal na contact, at ang eksaktong mga salitang sasabihin.',
      how4t: 'Subaybay',
      how4d: 'I-save ang confirmation number mo at makakuha ng follow-up date.',
      demoText: 'Hindi kinuha ang aming basura at hindi kayang ilipat ng nanay ko ang mga basurahan nang mag-isa.',
      clarifySure: 'gusto naming maging sigurado bago ka namin ipadala kahit saan.',
      confSaved: '✓ Nai-save ang confirmation — may lakas na ang follow-up mo.',
      confEmpty: 'Ilagay muna ang confirmation o reference number — walang laman ang field.',
      confSame: 'Naka-save na ang confirmation na iyan.',
      receiptLangNote: 'Ang mga receipt ay nakasulat sa English o Español — ang mga wikang ginagamit ng lungsod. Ang mga button at menu ay nananatili sa wika mo.',
      emNote: 'Ang mga detalye ng emergency ay ipinapakita sa English. Ang 9-1-1 ay gumagana sa English at Español.',
      altH: 'Hindi ganap na tama? Baka mas angkop ang isa sa mga ito:',
      reportIssue: 'Maling numero o patay na link? I-report ito',
      emailDraft: 'Buksan ang email draft',
      emailHint: 'Binubuksan ang mail app mo nang nakasulat na ang mensahe. I-paste ang opisyal na address mula sa mga source link sa itaas — hindi kami kailanman mismo nagpapadala ng anumang bagay.',
      copyScript: 'Kopyahin ang script',
      scriptCopied: '✓ Nakopya ang script — basahin ito nang malakas kapag tumawag ka.',
      lastVerified: 'HULING BERIPIKADO',
      srcVerified: 'beripikado',
      srcMaintainer: 'Tagapangasiwa',
      srcNext: 'Susunod na review',
      msgReportTpl: 'Kumusta — nais kong mag-report ng: {title}, malapit sa {loc}. Ganito na ito simula {since}. Maaari ba ninyo akong bigyan ng service request number para sa report na ito? (Kaso {caseId})',
      msgFollowTpl: 'Kumusta — nag-follow up ako sa {title}, na ni-report noong {date}. Ang service request number ko ay {conf}. Ano na ang kasalukuyang status, at kailan ako makakapag-asam ng aksyon? (Kaso {caseId})',
      msgEscalateTpl: 'Kumusta — ni-report ko ang {title} noong {date}, request number {conf}. Lumipas na ang follow-up date kong {followUpDate} nang walang update. Maaari ba itong i-eskala, at sino ang nagpapangasiwa ng kaso? (Kaso {caseId})',
      phLoc: '[mga kalapit na kanto o tinatayang address]',
      phSince: '[petsa ng unang pagkakita mo rito]',
      phDate: '[petsa]',
      phConf: '[request number]',
      dayToday: 'Ngayon',
      dayBy: 'Bago ang ',
      stHeard: 'NATANGGAP',
      stClassified: 'NAITUGMA',
      stReady: 'HANDA NA',
      stSubmitted: 'NAISUMITE',
      stFollowup: 'KAILANGAN ANG FOLLOW-UP',
      stResolved: 'NALUTAS',
      tlHeard: 'Inilarawan mo ang problema sa sarili mong salita.',
      tlClassified: 'Naitugma sa {title} ({pct}%).',
      tlReady: 'Handa na ang listahan ng ebidensya at ang opisyal na contact.',
      tlSubSaved: 'Nai-save ang confirmation: {conf}',
      tlSubWait: 'Hinihintay na makipag-ugnayan ka sa lungsod at i-save ang confirmation mo.',
      tlFollowDue: 'Bumalik at mag-check kung wala ka pang naririnig.',
      tlResolvedY: 'Minarkahan mo itong nalutas.',
      tlResolvedN: 'Hindi pa.',
      tlCaseDeleted: 'Binura ang case',
      tlCaseDeletedBody: 'Tinanggal sa device na ito ang lahat ng detalye ng case na ito.',
      statCases: 'Mga case',
      statResolved: 'Beripikadong nalutas',
      statDue: 'May due na follow-up',
      statRate: 'Rate ng resulta',
      gcalTitlePfx: 'Follow-up: ',
      fnl1: 'Sinimulan ang report',
      fnl2: 'Nailarawan ang problema',
      fnl3: 'Inirekomenda ang serbisyo',
      fnl4: 'Naihanda ang ebidensya',
      fnl5: 'Nabuksan ang opisyal na aksyon',
      fnl6: 'Naitala ang confirmation',
      fnl7: 'Naberipika ang resulta',
      evl_report_started: 'Sinimulan ang report',
      evl_language_selected: 'Pinalitan ang wika',
      evl_issue_description_entered: 'Nailarawan ang problema',
      evl_clarification_shown: 'Ipinakita ang isang mabilisang tanong',
      evl_route_recommended: 'Inirekomenda ang serbisyo',
      evl_route_manually_selected: 'Manu-manong pinili ang serbisyo',
      evl_evidence_checklist_completed: 'Natapos ang checklist ng ebidensya',
      evl_official_handoff_opened: 'Nabuksan ang opisyal na contact',
      evl_confirmation_saved: 'Nai-save ang confirmation',
      evl_follow_up_scheduled: 'Naka-iskedyul ang follow-up',
      evl_case_reopened: 'Muling binuksan ang case',
      evl_case_marked_resolved: 'Minarkahang nalutas',
      evl_case_deleted: 'Binura ang case',
      evl_error_shown: 'May kinailangang atensyon',
      evl_emergency_gate_shown: 'Ipinakita ang emergency check',
      evl_message_copied: 'Nakopya ang mensahe',
      rawLog: 'Technical log (para sa mga auditor)',
      docTitle: 'COMPTON ONE: FIX — Isang problema. Isang malinaw na daan pasulong.',
      skipLink: 'Lumaktaw sa pangunahing nilalaman',
      footerMeta: 'MGA SOURCE HULING BERIPIKADO 2026-07-27 · SUSUNOD NA REVIEW 2026-08-26',
      reportWrongShort: 'I-REPORT ANG MALING NUMERO',
      yourCaseMark: '(ang case mo)'
  };
  var ZH = {
      eyebrow: '城市服务导航 · 加利福尼亚州康普顿',
      h1a: '一个问题。',
      h1b: '一条清晰的解决之路。',
      lede: '用您自己的话描述一个城市服务问题。COMPTON ONE: FIX 帮您准备所需的信息、找到官方的下一步，并跟踪事情的进展。',
      cta: '开始报告',
      ctademo: '运行演示场景',
      trust: '为清晰的下一步而设计。您的报告始终由您掌控。',
      supported: '我们目前可以指引的服务',
      howlabel: '工作原理',
      privacy: '我们只询问大致街区，不问您的确切地址。不需要政府身份证件。不公开报告人姓名。您可以随时删除个案。',
      disclosure: '黑客马拉松原型：本应用帮助您准备并跟踪您的行动，不会直接向康普顿市提交。',
      step1: '第 1 步，共 5 步——告诉我们发生了什么',
      step2: '第 2 步，共 5 步——一个简短的问题',
      step3: '第 3 步，共 5 步——您的行动计划 · 只差一个电话',
      step4: '第 4 步，共 5 步——别断了线索',
      step5: '第 5 步，共 5 步——您的个案',
      intakeH: '您不需要知道该找哪个部门。',
      what: '发生了什么？',
      whatHint: '就像跟邻居解释那样描述问题，越朴实的话越好用。（目前用英语或西班牙语描述匹配最准确。）',
      examples: '或者从一个例子开始：',
      intakePriv: '请不要包含姓名、车牌号，或针对某个具体人的指控。只描述您看到的情况。',
      analyze: '找到正确的路径',
      back: '← 返回',
      printFallback: '您的浏览器阻止了打印。请使用浏览器菜单 → 打印，或对这张回执截图。',
      clarifyH: '一个简短的问题',
      yes: '是的，没错',
      notsure: '不对，或者我不确定',
      chooseH: '这可能属于两种不同的服务',
      chooseHint: '我们没有足够的把握替您选择。请选择与您所见相符的一项。',
      unsupH: '我们无法匹配这一项',
      unsupBody: 'COMPTON ONE: FIX 可以指引 {n} 项城市服务，但我们不会替您猜测部门，因为猜错会浪费您的时间。请换个说法试试、在下方选择最接近的服务，或拨打康普顿市总机 (310) 605-5500。',
      saved: '下一步：跟踪这个个案',
      print: '打印或保存 PDF',
      edit: '修改我的回答',
      tlH: '个案时间线',
      confLabel: '您收到的确认编号',
      confHint: '填写市里给您的任何信息：服务申请编号、参考代码，或与您通话人员的日期和姓名。',
      confWhere: '这个编号从哪里来？您打电话或提交时市里会给您——请问："我能拿到这个报告的服务申请编号吗？"把他们给您的任何信息记在这里，跟进时才有凭据。',
      saveConf: '保存确认编号',
      resolve: '标记为已解决',
      del: '删除这个个案',
      simNote: '本原型中模拟的部分：短信提醒以及市里的任何确认回执。本页面上其他所有内容都是真实行为。',
      toDash: '查看我的个案 →',
      dashH: '您的个案',
      demoData: '演示数据。这些个案用于展示处理结果的闭环，不是真实的城市记录。',
      yourCases: '进行中和最近的',
      newReport: '再发起一份报告',
      footer: 'COMPTON ONE: FIX 是一个独立原型，不由康普顿市运营，也不会代您提交报告。',
      owner: '谁负责处理',
      evidence: '请准备这些资料',
      prohibited: '请勿包含',
      action: '采取官方的下一步',
      script: '该怎么说',
      save: '保存您收到的信息',
      follow: '跟进',
      sources: '信息来源',
      yousaid: '您告诉我们的情况',
      conf: '匹配置信度',
      notsub: '本原型不会代您向市里提交。',
      verified: '官方已核实',
      needsconf: '待确认',
      mCase: '个案',
      mStatus: '状态',
      useWhen: '适用情形',
      reaches: '受理方',
      noSla: '市里尚未公布这项服务的处理时限，所以这只是一个提醒您自己的时间点——而不是市里的承诺。',
      stopFirst: '如果您看到以下任何情况，请先停下并拨打 9-1-1：',
      empty: '请先描述发生了什么。',
      reopen: '重新打开这个个案',
      evDone: '已收集的证据',
      keepH: '把这个个案保留在这部手机上吗？',
      keepBody: '现在如果您关闭页面，这个个案就会消失。我们可以把它保存在这台设备上，方便您回来查看。保存的内容：您输入的文字、匹配到的服务、您的确认编号和跟进日期。不会发送到任何地方，也没有任何能识别您身份的信息。您可以用一个按钮全部清除。',
      keepYes: '保存在这台设备上',
      keepNo: '不用，暂时保留就好',
      keepOn: '仅保存在这台设备上',
      keepOff: '未保存——关闭页面后这个个案即结束',
      keepFail: '这台设备不允许我们保存。个案仍可使用，但关闭页面后将无法保留。',
      erase: '清除所有已保存的内容',
      erased: '这台设备上保存的所有内容已清除。',
      savedCases: '已保存在这台设备上',
      noSaved: '这台设备上还没有保存任何内容。',
      openCase: '打开',
      cal: '下载日历文件（.ics）',
      gcal: '添加到 Google 日历',
      calDone: '✓ 提醒已下载。打开文件即可把跟进日期加入您的日历——或使用 Google 日历按钮一键添加。',
      gcalDone: '✓ 正在打开 Google 日历——请检查活动并点击保存。',
      msgH: '消息工作室',
      msgHint: '为市里准备好的现成文字。把 [方括号] 里的内容填好，然后复制粘贴到市里的表格、电子邮件或您的笔记中。',
      msgReport: '首次报告',
      msgFollow: '跟进',
      msgEscalate: '升级',
      msgCopy: '复制消息',
      msgCopied: '✓ 已复制——请粘贴到市里的表格、电子邮件或您的笔记中。',
      nextH: '接下来会发生什么',
      nextS1: '收集上面的资料，边做边打勾。',
      nextS2: '采取官方的下一步——打电话或打开表格。下面的通话稿和消息就是您要说的内容。',
      nextS3: '索要服务申请编号或确认编号，然后进入跟踪环节。',
      nextS4: '在跟进日期回来看看，并记录发生了什么。',
      evReady: '所有资料已准备好，您可以联系市里了。',
      evReadyBtn: '前往官方的下一步 ↓',
      evDoneBtn: '我已联系市里——保存我的确认编号 →',
      afterContactText: '已经联系市里了？保存他们给您的确认编号，跟进时才有凭据。',
      afterContactBtn: '保存我的确认编号 →',
      privLabel: '本应用记录了关于您的哪些信息',
      privNote: '本次会话产生的每一个事件都完整列在下方。您输入的描述、地址和确认编号都不可能进入这个日志——分析层只接受简短的固定标识符，其他一律拒绝。不会发送到任何地方，只留在您的设备上。',
      evLabel: '会话事件日志',
      evNone: '还没有记录任何事件。',
      stepNames: '描述|匹配|行动|跟踪|已解决',
      how1t: '描述',
      how1d: '用您自己的话说发生了什么，不需要知道部门名称。',
      how2t: '匹配',
      how2d: '我们把它匹配到 {n} 项经过核实的城市服务之一，并向您展示信息来源。',
      how3t: '行动',
      how3d: '您会拿到证据清单、官方联系方式和确切的措辞。',
      how4t: '跟踪',
      how4d: '保存您的确认编号，并获得一个跟进日期。',
      demoText: '我们的垃圾被漏收了，我妈妈一个人搬不动垃圾桶。',
      clarifySure: '我们想在给您指路之前先确认清楚。',
      confSaved: '✓ 确认编号已保存——您的跟进现在有凭据了。',
      confEmpty: '请先填写确认编号或参考编号——输入框是空的。',
      confSame: '这个确认编号已经保存过了。',
      receiptLangNote: '回执以英语或西班牙语书写——这是市里工作使用的语言。按钮和菜单仍保持您选择的语言。',
      emNote: '紧急情况信息以英语显示。9-1-1 可使用英语和西班牙语。',
      altH: '不太对？以下可能更合适：',
      reportIssue: '号码错误或链接失效？报告这个问题',
      emailDraft: '打开邮件草稿',
      emailHint: '打开您的邮件应用，消息已为您写好。请从上面的来源链接中复制官方地址粘贴进去——我们从不代您发送任何内容。',
      copyScript: '复制通话稿',
      scriptCopied: '✓ 通话稿已复制——打电话时照着念。',
      lastVerified: '最近核实',
      srcVerified: '已核实',
      srcMaintainer: '维护者',
      srcNext: '下次复核',
      msgReportTpl: '您好——我想报告：{title}，位置在{loc}附近。从{since}起就一直这样。您能给我这个报告的服务申请编号吗？（个案 {caseId}）',
      msgFollowTpl: '您好——我想跟进{title}，于{date}报告。我的服务申请编号是{conf}。请问目前进展如何，我什么时候能看到处理？（个案 {caseId}）',
      msgEscalateTpl: '您好——我于{date}报告了{title}，申请编号{conf}。我的跟进日期{followUpDate}已经过了，仍没有任何更新。这件事可以升级处理吗？由谁在负责这个个案？（个案 {caseId}）',
      phLoc: '[最近的交叉路口或大致地址]',
      phSince: '[您第一次看到的日期]',
      phDate: '[日期]',
      phConf: '[申请编号]',
      dayToday: '今天',
      dayBy: '截止',
      stHeard: '已收到',
      stClassified: '已匹配',
      stReady: '已就绪',
      stSubmitted: '已提交',
      stFollowup: '待跟进',
      stResolved: '已解决',
      tlHeard: '您用自己的话描述了这个问题。',
      tlClassified: '已匹配到{title}（{pct}%）。',
      tlReady: '证据清单和官方联系方式已准备好。',
      tlSubSaved: '确认编号已保存：{conf}',
      tlSubWait: '等待您联系市里并保存确认编号。',
      tlFollowDue: '如果还没有任何消息，请回来查看。',
      tlResolvedY: '您已将其标记为已解决。',
      tlResolvedN: '还没有。',
      tlCaseDeleted: '个案已删除',
      tlCaseDeletedBody: '这个个案的所有详情已从这台设备上移除。',
      statCases: '个案数',
      statResolved: '经核实已解决',
      statDue: '待跟进',
      statRate: '解决率',
      gcalTitlePfx: '跟进：',
      fnl1: '开始报告',
      fnl2: '描述了问题',
      fnl3: '推荐了服务',
      fnl4: '备好了证据',
      fnl5: '打开了官方渠道',
      fnl6: '记录了确认编号',
      fnl7: '核实了结果',
      evl_report_started: '开始报告',
      evl_language_selected: '切换了语言',
      evl_issue_description_entered: '描述了问题',
      evl_clarification_shown: '显示了澄清问题',
      evl_route_recommended: '推荐了服务',
      evl_route_manually_selected: '手动选择了服务',
      evl_evidence_checklist_completed: '完成了证据清单',
      evl_official_handoff_opened: '打开了官方联系方式',
      evl_confirmation_saved: '保存了确认编号',
      evl_follow_up_scheduled: '安排了跟进',
      evl_case_reopened: '重新打开了个案',
      evl_case_marked_resolved: '标记为已解决',
      evl_case_deleted: '删除了个案',
      evl_error_shown: '出现了需要注意的提示',
      evl_emergency_gate_shown: '显示了紧急提示',
      evl_message_copied: '复制了消息',
      rawLog: '技术日志（供审计人员查看）',
      docTitle: 'COMPTON ONE: FIX —— 一个问题。一条清晰的解决之路。',
      skipLink: '跳转到主要内容',
      footerMeta: '来源最近核实 2026-07-27 · 下次复核 2026-08-26',
      reportWrongShort: '报告错误号码',
      yourCaseMark: '（您的个案）'
  };
  T.tl = Object.assign({}, T.en, TL);
  T.zh = Object.assign({}, T.en, ZH);

  // Emergency guidance exists in en/es only inside the bundle; fall back to
  // English (the render layer shows a translated note explaining why).
  C1.EMERGENCY_GUIDANCE.tl = C1.EMERGENCY_GUIDANCE.en;
  C1.EMERGENCY_GUIDANCE.zh = C1.EMERGENCY_GUIDANCE.en;

  // Receipts are issued in en/es — the city's working languages. Coerce at
  // the boundary so buildReceipt can never dereference an undefined locale.
  var _buildReceipt = C1.buildReceipt.bind(C1);
  C1.buildReceipt = function (text, cls, opts) {
    opts = opts || {};
    if (opts.lang && opts.lang !== 'en' && opts.lang !== 'es') {
      opts = Object.assign({}, opts, { lang: 'en' });
    }
    return _buildReceipt(text, cls, opts);
  };

  // Catalog service titles; trigger examples stay in en/es on purpose —
  // they are routing prompts, and intake matching runs in en/es.
  var TITLES = {
    illegal_dumping: { tl: 'Ilegal na pagtatapon', zh: '非法倾倒' },
    pothole: { tl: 'Lubak o sira ng kalsada', zh: '路面坑洞或道路损坏' },
    streetlight: { tl: 'Patay na ilaw ng kalye', zh: '路灯故障' },
    missed_trash: { tl: 'Hindi nakuhang basura', zh: '垃圾漏收' },
    water_or_sewer: { tl: 'Problema sa tubig o imburnal', zh: '供水或下水道问题' },
    graffiti: { tl: 'Pag-alis ng graffiti', zh: '涂鸦清除' },
    abandoned_vehicle: { tl: 'Inabanduna o sirang sasakyan', zh: '废弃或报废车辆' },
    sidewalk: { tl: 'Sira o umbok na bangketa', zh: '人行道破损或隆起' },
    street_tree: { tl: 'Problema sa puno sa kalye', zh: '街道树木问题' },
    traffic_sign_signal: { tl: 'Traffic signal, senyal, o marka ng kalye', zh: '交通信号灯、标志或路面标线' },
    storm_drain: { tl: 'Storm drain o baha sa kalye', zh: '雨水排水口或街道积水' },
    bulky_item: { tl: 'Pagkuha ng malalaking gamit o appliance', zh: '大件物品或家电上门收取' },
    recycling_ewaste: { tl: 'Recycling, e-waste, at mga delikadong gamit', zh: '回收、电子垃圾与有害物品' },
    animal_control: { tl: 'Animal control', zh: '动物管理' },
    code_violation: { tl: 'Paglabag sa ari-arian o code', zh: '房产或法规违规' },
    housing_help: { tl: 'Tulong sa pabahay at upa', zh: '住房与租金援助' },
    parking_citation: { tl: 'Parking ticket — bayaran o i-apela', zh: '停车罚单——缴纳或申诉' },
    utility_billing: { tl: 'Bill ng tubig o utility account', zh: '水费账单或公用事业账户' },
    business_permit: { tl: 'Lisensya ng negosyo o building permit', zh: '营业执照或建筑许可' },
    public_records: { tl: 'Mga public record at dokumento ng lungsod', zh: '公共档案与城市文件' },
    power_outage: { tl: 'Kawalan ng kuryente', zh: '停电' },
    homeless_outreach: { tl: 'Abot-tulong at suporta sa mga walang tirahan', zh: '无家可归者外展援助' }
  };
  Object.keys(TITLES).forEach(function (id) {
    var r = C1.serviceCatalog[id];
    if (!r) return;
    r.title.tl = TITLES[id].tl;
    r.title.zh = TITLES[id].zh;
    r.triggerExamples.tl = r.triggerExamples.en;
    r.triggerExamples.zh = r.triggerExamples.en;
  });

  // Tile-group labels (order matches TILE_GROUPS in app.js).
  var GROUPS = [
    { tl: 'Mga kalsada at ilaw', zh: '街道与照明' },
    { tl: 'Basura at ang bloke', zh: '垃圾与街区' },
    { tl: 'Bahay, tubig, at ari-arian', zh: '住宅、供水与房产' },
    { tl: 'Mga tao at city hall', zh: '居民与市政厅' }
  ];
  if (X.TILE_GROUPS) X.TILE_GROUPS.forEach(function (g, i) {
    if (GROUPS[i]) { g.tl = GROUPS[i].tl; g.zh = GROUPS[i].zh; }
  });

  // The controller's debris clarify question.
  if (X.DEBRIS_QUESTION) {
    X.DEBRIS_QUESTION.tl = 'Ito ba ay materyal na may nagtapon sa pampublikong lupa — tulad ng scrap metal, baso, o gulong — at hindi sira sa mismong bangketa o kalsada?';
    X.DEBRIS_QUESTION.zh = '这是有人倾倒在公共地面上的东西（如废金属、玻璃或轮胎），而不是人行道或街道本身的损坏吗？';
  }
})();
